<a href="https://colab.research.google.com/github/RickyMacharm/PyTorch/blob/master/01_PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Understanding PyTorch Tensors**

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

Computation in PyTorch is driven by what has come to be called PyTorch Tensors. Most of the patterns that are found in Numpy Arrays can be transformed into PyTorch Tensors.

In computer vision problems, images can easily be broken down into a few hundred features. 

Therefore, tensors can be best viewed as containers that wrap and store data features in the context of machine learning and deep learning, and are sort of a generalized representation of vectors and matrices. 

Before we proceed, we need to understand some words: _**scalars**_, _**vectors**_ and _**matrices**_.

**A scalar** is a zero-order tensor that only contains a single element, such as x1. In real life, examples of scalar representations include: length, time, distance,area,speed, temperature,energy, power and mass.

**Vectors** are first-order tensor since they only have one axis. In Python vectors are usually encapsulated in square brackets like a `list` and is represented thus:
```python
[x1, x2, x3,..]
``` 

**A matrix** is a second-order tensor that has two axes. In Python it is represented as a `list` of lists:
```python
[ [x11, x12, x13..] , [x21, x22, x23..] , [x31, x32, x33..] ]
``` 

The images below will explain these concepts a lot more:

![picture](https://drive.google.com/uc?id=1-0BMtiJ70f6uN7SFE6eSxRvFQxFrCg76)

## **How to create PyTorch Tensors from Python lists**

There are multiple ways to create a tensor in PyTorch. We will look at a few of them after we are done with some basics.

I have written the codes in here, try and copy them and run them yourself in new cells.

### **create a tensor with all ones**

1. Let's start by importing the `Torch` library
```python
import torch
```
2. We will use the `ones()` method. The parameters used is to show the order or shape of the tensor. The inputed parameters of the shape`(2,3)` tells Python to form a tensor of 2 vectors with 3 entries per vector. Since we are dealing with ones, this command will form $2$ vectors (in list form) with $3$ ones in each. Changing the parameters will confirm what we are doing.
```python
torch.ones((2,3))
```
This will return a tensor that contains ones and has a default `float`
datatype
```python
tensor([[1., 1., 1.],
[1., 1., 1.]])
```
We can create a tensor consisting of only integer ones. What we need to do is to add datatype (dtype) as a parameter
```python
torch.ones((2,3), dtype=torch.int8)
```
which will return a tensor consisting only of integer ones
```python
tensor([[1, 1, 1],
[1, 1, 1]], dtype=torch.int8)
```
We can also create a tensor consisting of only integer zeros, doing exactly the same as before, but using the `zeros()` method
```python
torch.zeros((2,3), dtype=torch.int8)
```
This will return a tensor consisting of only integer zeros
```python
tensor([[0, 0, 0],
[0, 0, 0]], dtype=torch.int8)
```
### **create a tensor filled with a specific value**
 $\pi = 3.14159265358979323846264338327950288419$.

We will use the `full()` method and pass in the required fill value along
with the shape
```python
torch.full((2, 3), 3.14159265358979323846264338327950288419)
```
This will return a tensor with the given value rounded up.
```python
tensor([[3.1416, 3.1416, 3.1416],
[3.1416, 3.1416, 3.1416]])
```
### **Use the `rand()` method create a tensor from a uniform distribution**
```python
torch.rand((2,3))
```
Which will draw a tensor with random values from a uniform distribution
from $[0, 1]$
```python
tensor([[0.6714, 0.0930, 0.4395],
[0.5943, 0.6582, 0.6573]])
```
### **Use the `randn()` method create a tensor with mean $0$ and variance $1$**
```python
torch.randn((2,3))
```
The output will draw a tensor with random values with mean $0$ and variance $1$
from a normal distribution, also called the standard normal distribution
```python
tensor([[ 0.3470, -0.4741, 1.2870],
[ 0.8544, 0.9717, -0.2017]])
```
### **Use the `rand_int()` method**
We will pass in the lower limit, the
upper limit, and the shape to create a tensor from a given range of values
```python
torch.randint(10, 100, (2,3))
```
The output to  this will return a tensor between $10$ and $100$, similar to the following
```python
tensor([[63, 93, 68],
[93, 58, 29]])
```
### **Creating  a tensor from existing data**
We will use the `tensor` class for this
```python
torch.tensor([[1, 2 ,3], [4, 5, 6]])
```
This will create a copy of the data and create a tensor. If you want
to avoid making a copy, you could use 
```python
torch.as_tensor([[1,
2 ,3], [4, 5, 6]])
```
The output returns a tensor with the same datatype as that of the data, which in
this case is an integer tensor
```python
tensor([[1, 2, 3],
[4, 5, 6]])
```
We should note that, if one of the data values is a float, then all of the
values would be converted into a float; however, if one of the
values is a string, then an error is thrown.

### **create a tensor with the attributes from another tensor**
 Let's first create a reference tensor for this and store it into a variable called `a`
 ```python
a = torch.tensor([[1, 2 ,3], [4, 5, 6]])
```
Let's see the datatype of tensor a
```python
a.dtype
```
output
```python
torch.int64
```
Now let's look at the shape of the tensor
```python
a.shape
```
output
```python
torch.Size([2, 3])
```
if we are okay with the datatype and shape, we will create a tensor
`b` so that it matches the attributes of `a` 
```python
b = torch.ones_like(a)
b
```
output
```python
tensor([[1, 1, 1],
[1, 1, 1]])
```

**_I advise you to test these concepts using the cells of your Jupyter notebook or colab_**.



In [0]:
import torch

In [0]:
torch.ones((2,3), dtype=torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)