<a href="https://colab.research.google.com/github/RickyMacharm/PyTorch/blob/master/03_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors in PyTorch**
While working with tensors and dealing with neural networks, we often need to go
through and rearrange data in the tensors so that the dimensions of the tensors fit the needs
of the architecture. In this section, we will explore common rearrangement and reshaping
techniques in PyTorch.

**The `.reshape()` method:** `.reshape(a, b)` returns a new tensor with the same
data as the original tensor with size (a, b) as it copies the data to another part
of memory; `.reshape()` can operate on both contiguous and noncontiguous
tensors, and may return a copy or a view of the original tensor.

In [3]:
import torch
# We create a tensor we call a
a = torch.Tensor([1, 2, 3, 4]); a

tensor([1., 2., 3., 4.])

In [4]:
torch.reshape(a, (2, 2))

tensor([[1., 2.],
        [3., 4.]])

In [8]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.shape, a

(torch.Size([6]), tensor([1., 2., 3., 4., 5., 6.]))

**The `.resize()` method:** `.resize_(a, b)` returns the same tensor without
creating a copy with the new given shape. But we should keep in mind that, if
the new shape results in fewer elements than the original tensor, then it won't
throw any error, and some elements will be removed from the tensor but not
from memory. If the new shape results in more elements than the original tensor,
new elements will be uninitialized in memory without throwing any error.

In [9]:
a.resize_((2, 2))

tensor([[1., 2.],
        [3., 4.]])

The most common method is `view()` method

**The .view() method:** `.view(a, b)` will return a new tensor with the same
data as weights with size (a, b); `.view()` can only operate on a contiguous tensor
and returns the same storage as the input.

In [10]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.view((2, 3))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

With the `view()` method, you can choose not to mention one of the dimensions
and arrange the rest of them, and PyTorch will calculate the missing dimension

In [11]:
a.view((2, -1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [16]:
a = [[1,2,3,4],[5,2,4,7],[6, 4, 2, 5]]
b = torch.Tensor(a);b

tensor([[1., 2., 3., 4.],
        [5., 2., 4., 7.],
        [6., 4., 2., 5.]])

In [17]:
b.shape

torch.Size([3, 4])

In [18]:
torch.reshape(b, (4, 3))

tensor([[1., 2., 3.],
        [4., 5., 2.],
        [4., 7., 6.],
        [4., 2., 5.]])

In [20]:
b.view((2, -1))

tensor([[1., 2., 3., 4., 5., 2.],
        [4., 7., 6., 4., 2., 5.]])

In [21]:
b

tensor([[1., 2., 3., 4.],
        [5., 2., 4., 7.],
        [6., 4., 2., 5.]])

In [22]:
b.view((6, -1))

tensor([[1., 2.],
        [3., 4.],
        [5., 2.],
        [4., 7.],
        [6., 4.],
        [2., 5.]])

In [23]:
b.view((12, -1))

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [2.],
        [4.],
        [7.],
        [6.],
        [4.],
        [2.],
        [5.]])

In [24]:
b.view((1, -1))

tensor([[1., 2., 3., 4., 5., 2., 4., 7., 6., 4., 2., 5.]])

I think I love the `view` method.


You can use the dimension of another tensor and make a given tensor resemble the
dimension of that tensor without affecting the actual dimensions of either of them by using the `view_as` function.

In [26]:
x = torch.Tensor([[1, 2, 3],[4, 5, 6]]); x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [27]:
y =  torch.Tensor([4,5,6,7,8,9]);y

tensor([4., 5., 6., 7., 8., 9.])

In [28]:
y.view_as(x)

tensor([[4., 5., 6.],
        [7., 8., 9.]])

In [29]:
x.view_as(y)

tensor([1., 2., 3., 4., 5., 6.])

In [30]:
x,y

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([4., 5., 6., 7., 8., 9.]))